sudo: false
language: node_js
node_js:
- '6'

env:
  global:
    - SAUCE_USERNAME=opbeat-react
    - SAUCE_ACCESS_KEY=699838bc-49b3-4c92-adf0-690ba855e0d6
  matrix:
    # Order: a slower build first, so that we don't occupy an idle travis worker waiting for others to complete.
    # - MODE=saucelabs_optional
    - MODE=saucelabs

cache:
  directories:
  - node_modules

addons:
 firefox: "38.0"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
